export const themes = {
  cars: {
    main_color: [
      "#F5BF55",
      "#4CAAFF",
      "#FF7070",
      "#E9AF2F",
      "#E46F95",
      "#197b9e",
      "#D9BFFF",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#9AA2AC", "#283849", "#E0E0E0"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "olympic",
    text_color: "#232323",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Roboto",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Roboto",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Roboto",
        "font-weight": "bold",
        "font-style": "italic",
      },
      value: {
        "font-size": "h4",
        "font-family": "Roboto",
        "font-weight": "bold",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Roboto",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#526cee",
    context_color: "#CDD9E4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  cars2: {
    main_color: [
      "#F4AD7A",
      "#E595B0",
      "#F7CC72",
      "#70C3E4",
      "#D480D1",
      "#5E8E7C",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#BEC4C9", "#5F6F78"],
    similar_to_bcg: ["#E7E7E7", "#F6F6F6"],
    other_colors: [],
    num_of_colors: 5,
    topic: "science and technology",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Roboto",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Roboto",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Roboto",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Roboto",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Roboto",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#60b898",
    context_color: "#C7CACB",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  olympic: {
    main_color: [
      "#8AAD2E",
      "#FCA516",
      "#FE8A5C",
      "#E9AF2F",
      "#E46F95",
      "#197b9e",
      "#D9BFFF",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#9AA2AC", "#283849", "#E0E0E0"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "olympic",
    text_color: "#232323",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Roboto",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Roboto",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Roboto",
        "font-weight": "bold",
        "font-style": "italic",
      },
      value: {
        "font-size": "h4",
        "font-family": "Roboto",
        "font-weight": "bold",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Roboto",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#526cee",
    context_color: "#CDD9E4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  spotify: {
    main_color: [
      "#F4AD7A",
      "#F7CC72",
      "#E595B0",
      "#70C3E4",
      "#D480D1",
      "#5E8E7C",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#BEC4C9", "#5F6F78"],
    similar_to_bcg: ["#E7E7E7", "#F6F6F6"],
    other_colors: [],
    num_of_colors: 5,
    topic: "science and technology",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Roboto",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Roboto",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Roboto",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Roboto",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Roboto",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#60b898",
    context_color: "#C7CACB",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  1: {
    main_color: [
      "#8AAD2E",
      "#FCA516",
      "#FE8A5C",
      "#E9AF2F",
      "#E46F95",
      "#197b9e",
      "#D9BFFF",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#9AA2AC", "#283849", "#E0E0E0"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "olympic",
    text_color: "#232323",
    font: {
      title: {
        "font-size": "h1",
        "font-family":
          '"Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Verdana, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Trebuchet MS", sans-serif',
        "font-weight": "bold",
        "font-style": "italic",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#526cee",
    context_color: "#CDD9E4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  189: {
    main_color: [
      "#0060DC",
      "#CE9800",
      "#DD4E00",
      "#009A8B",
      "#AF8D00",
      "#0097D2",
      "#A33900",
      "#663399",
      "#005252",
      "#E67A8C",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#A0A8B2", "#55687B", "#223851"],
    similar_to_bcg: ["#F6F6F6"],
    other_colors: [],
    num_of_colors: 6,
    topic: "health",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#0060DC",
    context_color: "#AABEC6",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  1201: {
    main_color: [
      "#A84F7C",
      "#003D7A",
      "#5EA65D",
      "#D28B8F",
      "#9E3D32",
      "#766099",
      "#4C7D91",
      "#E6C74D",
      "#B17B4C",
      "#66935C",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#000200", "#AFAFAF", "#5A5A5A", "#272D2A"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "politics and government",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Georgia, serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#003D7A",
    context_color: "#AABEC4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  2320: {
    main_color: [
      "#8B5B7D",
      "#DE775B",
      "#EB983B",
      "#8B5BA8",
      "#C8A850",
      "#D58C84",
      "#5E8B9A",
      "#7D6A92",
      "#8D7A5C",
      "#5B8C7D",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#B5B5B5", "#C7D2E6", "#BFA0A4", "#788992"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 6,
    topic: "sport",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family":
          '"Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Verdana, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Trebuchet MS", sans-serif',
        "font-weight": "bold",
        "font-style": "italic",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#8B5B7D",
    context_color: "#C4C0C1",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  193: {
    main_color: [
      "#9F030A",
      "#8B4513",
      "#006400",
      "#0572D9",
      "#cbaf0e",
      "#4B0082",
      "#0D4374",
      "#DC143C",
      "#2E8B57",
      "#BDB76B",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#B5B5B5", "#DEB2B2", "#8B9DA6", "#012339"],
    similar_to_bcg: ["#E7E7E7"],
    other_colors: [],
    num_of_colors: 5,
    topic: "conflict, war and peace",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#0D4374",
    context_color: "#D3D3D3",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  1384: {
    main_color: [
      "#D9A800",
      "#5E3CDC",
      "#008C82",
      "#D64F00",
      "#DC7180",
      "#6F4E37",
      "#8B728E",
      "#B09F7D",
      "#4A7C59",
      "#9966CC",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#8E9BA8", "#334355", "#082239", "#ABD8ED"],
    similar_to_bcg: ["#EEEEEE"],
    other_colors: [],
    num_of_colors: 5,
    topic: "arts, culture, entertainment and media",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Trebuchet MS", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Garamond, serif",
        "font-weight": "normal",
        "font-style": "italic",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": '"Segoe UI Light", "Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "italic",
      },
    },
    base_color: "#008C82",
    context_color: "#B4D9E2",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  311: {
    main_color: [
      "#B12215",
      "#8B5ED0",
      "#BBA12D",
      "#BC184D",
      "#D9845B",
      "#8F4C2A",
      "#7A4D70",
      "#8C8239",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#2F435A", "#5E6F7D", "#8C8C92", "#B3A2BA"],
    similar_to_bcg: ["#F6F6F6"],
    other_colors: [],
    num_of_colors: 5,
    topic: "lifestyle and leisure",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Trebuchet MS", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "italic",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "italic",
      },
    },
    base_color: "#4A6E75",
    context_color: "#AABEC4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  476: {
    main_color: [
      "#c69d06",
      "#C45C8A",
      "#345D8C",
      "#6FA8D1",
      "#8EB338",
      "#AD6A47",
      "#5E8E7C",
      "#9A70AE",
      "#CC9645",
      "#4B6B5B",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#BEC4C9", "#5F6F78"],
    similar_to_bcg: ["#E7E7E7", "#F6F6F6"],
    other_colors: [],
    num_of_colors: 5,
    topic: "science and technology",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Consolas, monospace",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#345D8C",
    context_color: "#C7CACB",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  2340: {
    main_color: [
      "#CE0301",
      "#7D0C0A",
      "#C45484",
      "#CE9306",
      "#F08C82",
      "#D66AE6",
      "#9EDDD8",
      "#598C7F",
      "#BF7E2F",
      "#0D2744",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#506275", "#ADB7BE"],
    similar_to_bcg: ["#F6F6F6"],
    other_colors: [],
    num_of_colors: 7,
    topic: "politics and government",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Georgia, serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#0D2744",
    context_color: "#A8B4B8",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  792: {
    main_color: [
      "#80191C",
      "#C84F66",
      "#3A7B20",
      "#438E8C",
      "#E27B8F",
      "#5cad5a",
      "#C45D3B",
      "#9A4D7C",
      "#B1792B",
      "#5E6A3E",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#323835", "#545B59", "#0F2840"],
    similar_to_bcg: ["#D1D1D1"],
    other_colors: [],
    num_of_colors: 6,
    topic: "health",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#80191C",
    context_color: "#A0B5BD",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  1447: {
    main_color: [
      "#8B5CD7",
      "#005ED3",
      "#C80000",
      "#00A69D",
      "#D38C61",
      "#5E8C96",
      "#B34F5F",
      "#E6C847",
      "#3D7D54",
      "#8C6E3D",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#162D45", "#7D8894", "#B5BEC8", "#BBA0AD"],
    similar_to_bcg: ["#F6F6F6"],
    other_colors: [],
    num_of_colors: 5,
    topic: "science and technology",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Consolas, monospace",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#005ED3",
    context_color: "#AABCC0",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  1272: {
    main_color: [
      "#7fb874",
      "#C26C8B",
      "#dbb87d",
      "#F59861",
      "#448EE4",
      "#8B4513",
      "#2F4F4F",
      "#B06584",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#586878", "#909BA8", "#25374E"],
    similar_to_bcg: ["#C2CCD4"],
    other_colors: [],
    num_of_colors: 6,
    topic: "society",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Verdana, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Verdana, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Calibri, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#471079",
    context_color: "#AABEC4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  1136: {
    main_color: [
      "#4B4FAF",
      "#2F70AF",
      "#B00020",
      "#66B388",
      "#9955AA",
      "#0077B8",
      "#E09040",
      "#409090",
      "#A04070",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#000000", "#606060", "#97C5C5"],
    similar_to_bcg: ["#F6F6F6"],
    other_colors: [],
    num_of_colors: 5,
    topic: "crime, law and justice",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Courier New, monospace",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#4B4FAF",
    context_color: "#B0C4DE",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  505: {
    main_color: [
      "#825FB5",
      "#D9B400",
      "#3C9C93",
      "#AD4B6A",
      "#D33C3C",
      "#4B6E9C",
      "#7BA84C",
      "#B57B2F",
      "#9D5A3C",
      "#6A4B9D",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#19334B", "#506275", "#99A3AA"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "human interest",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Calibri, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#4B6E9C",
    context_color: "#A0B4BB",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  300: {
    main_color: [
      "#B15148",
      "#C87242",
      "#5E7F87",
      "#D8AC4F",
      "#8B5B6E",
      "#95B075",
      "#C49D6B",
      "#7A6C5D",
      "#A86F5D",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#BDBDBD", "#797979", "#040000"],
    similar_to_bcg: ["#EEEEEE"],
    other_colors: [],
    num_of_colors: 5,
    topic: "human interest",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Calibri, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#7A6C5D",
    context_color: "#D3CEC0",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  477: {
    main_color: [
      "#7B4D2B",
      "#C88B2A",
      "#4B2347",
      "#3C7BA6",
      "#C43B30",
      "#A8683D",
      "#E6C25C",
      "#6FAAD7",
      "#B04F3D",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#C3C3C3", "#EECAB2", "#3C505D", "#5F6F78"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "labour",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#4B2347",
    context_color: "#B8B3B5",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  1224: {
    main_color: [
      "#00289A",
      "#AC240B",
      "#2F80ED",
      "#D99600",
      "#005BB5",
      "#BF001D",
      "#6699FF",
      "#3366CC",
      "#8C220E",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#5A5A5A", "#BDBDBD", "#1F1317", "#F4C6C5"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 6,
    topic: "conflict, war and peace",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#c0610e",
    context_color: "#A09A9B",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  325: {
    main_color: [
      "#F4845B",
      "#C8BFE7",
      "#A8EB9E",
      "#8B8DC2",
      "#5EC67D",
      "#FFC72C",
      "#B0E0E6",
      "#F9B36B",
      "#E3A8D4",
      "#66DEE9",
    ],
    bcg: "#09293B",
    context_colors: ["#667485", "#F6F6F6", "#584B3F"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "human interest",
    text_color: "#FFFFFF",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Calibri, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#66DEE9",
    context_color: "#789AA7",
    mapColorDefault: "#153C52",
    mapColorLow: "#2A6E8C",
    mapColorHigh: "#6ACCE6",
  },
  1820: {
    main_color: [
      "#CA4C6B",
      "#C4523C",
      "#CE7A53",
      "#B94539",
      "#C89B2B",
      "#9E6C5E",
      "#5A5F6E",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#B5BEC8", "#8895A2", "#082239", "#F0D4BB"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 6,
    topic: "politics and government",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Georgia, serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#4A6E7C",
    context_color: "#AABEC4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  2039: {
    main_color: [
      "#4087E3",
      "#B70301",
      "#E27B00",
      "#007F70",
      "#7D4C9A",
      "#CDA34F",
      "#B25759",
      "#3D5A80",
      "#82A079",
      "#C84A3B",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#374A5C", "#8C8C8C", "#082239"],
    similar_to_bcg: ["#F6F6F6"],
    other_colors: [],
    num_of_colors: 5,
    topic: "politics and government",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Georgia, serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#3D5A80",
    context_color: "#AABEC4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  1131: {
    main_color: [
      "#B32D1C",
      "#2F7BBF",
      "#2C8C3C",
      "#001F3F",
      "#004B8C",
      "#A19C00",
      "#995B4C",
      "#2B6969",
      "#7F3F7F",
      "#405060",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#BDBDBD", "#69564A", "#6E8290"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 6,
    topic: "society",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Verdana, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Verdana, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Calibri, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#001F3F",
    context_color: "#C0C0C0",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  1391: {
    main_color: [
      "#3C9C41",
      "#205BA6",
      "#006600",
      "#552778",
      "#8FC461",
      "#294B8A",
      "#004D00",
      "#12847D",
      "#403D81",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#737272", "#212121", "#CBCBCB", "#374A5C", "#0F2840"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "environment",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Verdana, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Garamond, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#3b4745",
    context_color: "#AABEC4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  2122: {
    main_color: [
      "#FFD166",
      "#3A579A",
      "#0e6483",
      "#95B8E4",
      "#D25188",
      "#FFBF53",
      "#4CAF50",
      "#EF6C00",
      "#6D4C41",
      "#8E24AA",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#BDBDBD", "#2F4455", "#E9CACA"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 6,
    topic: "society",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Verdana, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Verdana, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Calibri, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#3A579A",
    context_color: "#B0C4DE",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  653: {
    main_color: [
      "#1A6A61",
      "#0058AB",
      "#7D0F11",
      "#7B823B",
      "#A88F3A",
      "#2E9B8D",
      "#007BF0",
      "#C8181B",
      "#A5AF4A",
      "#C49D40",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#6D7B8C", "#25374E", "#B4BEC6"],
    similar_to_bcg: ["#F6F6F6"],
    other_colors: [],
    num_of_colors: 5,
    topic: "economy, business and finance",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Georgia, serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#1A6A61",
    context_color: "#AABEC4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  676: {
    main_color: [
      "#609D3E",
      "#008FC5",
      "#006D9E",
      "#74A648",
      "#00587F",
      "#2E4D5B",
      "#A86F35",
      "#E0782C",
      "#8B5B4A",
      "#596B7A",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#9A9A9A"],
    similar_to_bcg: ["#CBCBCB", "#F6F6F6", "#E7E7E7"],
    other_colors: [],
    num_of_colors: 5,
    topic: "labour",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#00587F",
    context_color: "#D7D2D3",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },

  419: {
    main_color: [
      "#FF736D",
      "#6B64AC",
      "#FFD431",
      "#CC7090",
      "#2C9955",
      "#CBE0B3",
      "#8B5F9C",
      "#E8A740",
      "#59B5D0",
      "#A04070",
    ],
    bcg: "#09293B",
    context_colors: ["#74818D", "#F6F6F6", "#9FA9B0"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 6,
    topic: "economy, business and finance",
    text_color: "#FFFFFF",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Georgia, serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#CBE0B3",
    context_color: "#6D8D9A",
    mapColorDefault: "#153C52",
    mapColorLow: "#2A6E8C",
    mapColorHigh: "#6ACCE6",
  },
  1873: {
    main_color: [
      "#eec831",
      "#A4243B",
      "#d673a9",
      "#E63946",
      "#FF914D",
      "#8B5E3C",
      "#e18355",
      "#5A8B79",
      "#8A6C5B",
      "#5C6B73",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#BEC4C9"],
    similar_to_bcg: ["#F6F6F6"],
    other_colors: [],
    num_of_colors: 7,
    topic: "environment",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Verdana, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Garamond, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#5A8B79",
    context_color: "#A0B5BD",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  839: {
    main_color: [
      "#82B34B",
      "#E0773E",
      "#C84C40",
      "#3C6BB0",
      "#C2904B",
      "#5A8B6F",
      "#9A5C80",
      "#606D4D",
      "#8C5A3E",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#3C505D"],
    similar_to_bcg: ["#D1D1D1", "#E7E7E7"],
    other_colors: [],
    num_of_colors: 5,
    topic: "politics and government",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Georgia, serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#3C6BB0",
    context_color: "#C4BDC0",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  859: {
    main_color: [
      "#214D8A",
      "#963036",
      "#C01607",
      "#613B5B",
      "#608AB7",
      "#CE7B02",
      "#006C67",
      "#8B4513",
      "#556B2F",
      "#8A2BE2",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#BDBDBD", "#485C69", "#9A9A9A"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "arts, culture, entertainment and media",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Trebuchet MS", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Garamond, serif",
        "font-weight": "normal",
        "font-style": "italic",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": '"Segoe UI Light", "Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "italic",
      },
    },
    base_color: "#214D8A",
    context_color: "#C4BFBF",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  2153: {
    main_color: [
      "#D9A800",
      "#A83F3B",
      "#1E3B6E",
      "#677D9B",
      "#E85A3F",
      "#8B7E2B",
      "#597F87",
      "#BB6D4C",
      "#7A6C7A",
      "#4D5C75",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#9A9A9A", "#B7C5D2", "#3C5867"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "conflict, war and peace",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#1E3B6E",
    context_color: "#C7C7C7",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  1130: {
    main_color: [
      "#E65B5B",
      "#345FA5",
      "#009688",
      "#4CAF50",
      "#d59d10",
      "#7e1d90",
      "#FF7043",
      "#607D8B",
      "#D81B60",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#977968", "#1C0C00"],
    similar_to_bcg: ["#EEEEEE", "#CBCBCB", "#D1D1D1"],
    other_colors: [],
    num_of_colors: 5,
    topic: "science and technology",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Consolas, monospace",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#345FA5",
    context_color: "#B0BEC5",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  256: {
    main_color: [
      "#62111A",
      "#77419B",
      "#6A68C4",
      "#39A1E6",
      "#8B4513",
      "#2E8B57",
      "#C49A00",
      "#8A2BE2",
      "#4682B4",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#1C1C1C", "#B9D5E9"],
    similar_to_bcg: ["#E7E7E7", "#D5E2E9"],
    other_colors: [],
    num_of_colors: 5,
    topic: "labour",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#62111A",
    context_color: "#BBBBBB",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  2303: {
    main_color: [
      "#B33C6B",
      "#4C4D8F",
      "#E28B2E",
      "#995B8A",
      "#6F8558",
      "#C87A4F",
      "#59798C",
      "#A36B3B",
      "#8B4E7A",
      "#5D6E7E",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#A7A7A7", "#3C505D", "#F0D3CA"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 6,
    topic: "economy, business and finance",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Georgia, serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#4C4D8F",
    context_color: "#B3ACA9",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  775: {
    main_color: [
      "#4B569D",
      "#D359AA",
      "#0059AB",
      "#B06D63",
      "#C8A57B",
      "#609D5B",
      "#E28B3E",
      "#8B4E7D",
      "#4A828B",
      "#AD8A4B",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#C3C3C3", "#90A4AD", "#485C69"],
    similar_to_bcg: ["#F6F6F6"],
    other_colors: [],
    num_of_colors: 5,
    topic: "science and technology",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Consolas, monospace",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#0059AB",
    context_color: "#B5B0B1",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  968: {
    main_color: [
      "#009172",
      "#C77B1B",
      "#be867f",
      "#4D7298",
      "#7D5A5A",
      "#006D6D",
      "#995B72",
      "#5A5A5A",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#B5B5B5", "#798994", "#2F4455"],
    similar_to_bcg: ["#EEEEEE"],
    other_colors: [],
    num_of_colors: 5,
    topic: "conflict, war and peace",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#344195",
    context_color: "#A8A8A8",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  109: {
    main_color: [
      "#A06069",
      "#6C131F",
      "#C70000",
      "#1361AF",
      "#A184E2",
      "#e6c34a",
      "#E86421",
      "#347B98",
      "#7D4C7F",
      "#5A8B60",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#3D4F62", "#BEC4C9", "#082239"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 7,
    topic: "crime, law and justice",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Courier New, monospace",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#1361AF",
    context_color: "#AAB9BF",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  94: {
    main_color: [
      "#CA583C",
      "#3D6DB5",
      "#90AB4A",
      "#C89840",
      "#E27B50",
      "#5A8B7C",
      "#B06A58",
      "#D8B060",
      "#7095AB",
      "#8B7A50",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#65757E", "#929BA4"],
    similar_to_bcg: ["#D1D1D1"],
    other_colors: [],
    num_of_colors: 5,
    topic: "crime, law and justice",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Courier New, monospace",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#3D6DB5",
    context_color: "#CFC8CB",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  493: {
    main_color: [
      "#005DA6",
      "#007A5E",
      "#5E8C00",
      "#A61A00",
      "#A680A3",
      "#bf975b",
      "#2E8B57",
      "#A04000",
      "#4682B4",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#737272", "#BDBDBD", "#334B5C"],
    similar_to_bcg: ["#E8F0EE"],
    other_colors: [],
    num_of_colors: 6,
    topic: "environment",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Verdana, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Garamond, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#005DA6",
    context_color: "#C7C2C3",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  1022: {
    main_color: [
      "#471079",
      "#C64A0A",
      "#CE7A53",
      "#9D7AD7",
      "#7E88CB",
      "#2F7C8A",
      "#B02E5C",
      "#2A6041",
      "#5C4C9B",
      "#D9AC5E",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#5E6E7F", "#9FA9B0", "#374A5C", "#EECAB2"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "lifestyle and leisure",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Trebuchet MS", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "italic",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "italic",
      },
    },
    base_color: "#471079",
    context_color: "#A8B4B8",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  580: {
    main_color: [
      "#700A18",
      "#8A2BE2",
      "#006400",
      "#5C6AD0",
      "#198467",
      "#AE442C",
      "#A13460",
      "#6278A0",
      "#9A6B2E",
      "#2E8B57",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#000000", "#BFCBE8", "#9A9A9A"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 6,
    topic: "crime, law and justice",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Courier New, monospace",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#700A18",
    context_color: "#BFCFD8",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  2361: {
    main_color: [
      "#10998b",
      "#A9685F",
      "#13655A",
      "#c4a534",
      "#4D8C57",
      "#C8724D",
      "#5A5E7A",
      "#9A5B6F",
      "#3E738B",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#3D4F62", "#74818D", "#082239", "#C7A8A6"],
    similar_to_bcg: ["#F6F6F6"],
    other_colors: [],
    num_of_colors: 5,
    topic: "health",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#13655A",
    context_color: "#AABEC4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  1501: {
    main_color: [
      "#A8471F",
      "#8B0000",
      "#7b5f12",
      "#B85E00",
      "#C12B2B",
      "#7D5A3C",
      "#4D6868",
      "#5A555B",
      "#663333",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#949494", "#2F4455"],
    similar_to_bcg: ["#CBCBCB", "#EEEEEE"],
    other_colors: [],
    num_of_colors: 5,
    topic: "lifestyle and leisure",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Trebuchet MS", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "italic",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "italic",
      },
    },
    base_color: "#4D6868",
    context_color: "#CCCCCC",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  444: {
    main_color: [
      "#436CB5",
      "#1F92AE",
      "#C84E8D",
      "#c3a247",
      "#F28C69",
      "#df9c15",
      "#8B5F9E",
      "#5EA76E",
      "#B96544",
      "#6D5C8F",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#A1A1A1", "#6C7C87", "#2F4455"],
    similar_to_bcg: ["#D1D1D1"],
    other_colors: [],
    num_of_colors: 6,
    topic: "sport",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family":
          '"Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Verdana, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Trebuchet MS", sans-serif',
        "font-weight": "bold",
        "font-style": "italic",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#436CB5",
    context_color: "#AABEC1",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  101: {
    main_color: [
      "#BA5244",
      "#D47A5C",
      "#A83E32",
      "#8B744A",
      "#4A687D",
      "#5E7F6A",
      "#C13E57",
      "#6F5A7B",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#BDBDBD", "#606060", "#828E95", "#2F4455"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "crime, law and justice",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": '"Times New Roman", Times, serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Courier New, monospace",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#8B744A",
    context_color: "#B7A8AA",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  770: {
    main_color: [
      "#C8507D",
      "#00639E",
      "#D95E42",
      "#59AFC8",
      "#62A037",
      "#9A4269",
      "#C98A00",
      "#3C7B58",
      "#824C27",
      "#405B86",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#B5B5B5"],
    similar_to_bcg: ["#F6F6F6", "#F6F6F6"],
    other_colors: [],
    num_of_colors: 5,
    topic: "economy, business and finance",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Georgia, serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#00639E",
    context_color: "#B5B0B1",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  110: {
    main_color: [
      "#FF7F50",
      "#9932CC",
      "#6A5ACD",
      "#C49A00",
      "#6495ED",
      "#20B2AA",
      "#9370DB",
      "#FF69B4",
      "#4682B4",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#949494", "#4B5C69"],
    similar_to_bcg: ["#CBCBCB", "#EEEEEE"],
    other_colors: [],
    num_of_colors: 5,
    topic: "human interest",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Calibri, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#4682B4",
    context_color: "#CCCCCC",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  1214: {
    main_color: [
      "#0053A5",
      "#B8271B",
      "#d9580d",
      "#be9a09",
      "#7EA641",
      "#5A6E8D",
      "#A84F00",
      "#00796B",
      "#8B5B47",
      "#595C7A",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#314455", "#A0A8B2", "#576876", "#D7ABA9"],
    similar_to_bcg: ["#EEEEEE"],
    other_colors: [],
    num_of_colors: 5,
    topic: "labour",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Tahoma, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#0053A5",
    context_color: "#A0B5BD",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  2493: {
    main_color: [
      "#F5D973",
      "#D9BFFF",
      "#5AB1FF",
      "#FF6B59",
      "#4DD0BD",
      "#FFC107",
      "#9CCC65",
      "#FFA07A",
      "#80DEEA",
      "#C0CA33",
    ],
    bcg: "#000D20",
    context_colors: ["#9AA2AC", "#283849", "#E0E0E0"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "sport",
    text_color: "#FFFFFF",
    font: {
      title: {
        "font-size": "h1",
        "font-family":
          '"Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Verdana, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Trebuchet MS", sans-serif',
        "font-weight": "bold",
        "font-style": "italic",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#D9BFFF",
    context_color: "#5A6E8F",
    mapColorDefault: "#112135",
    mapColorLow: "#4B4999",
    mapColorHigh: "#A899F7",
  },
  1990: {
    main_color: [
      "#82B34B",
      "#C85750",
      "#DE7A3B",
      "#2E467F",
      "#C9A61F",
      "#2C8DF8",
      "#572F4C",
      "#6FA85D",
      "#7D5C4C",
      "#A86F45",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#5E6E7F"],
    similar_to_bcg: ["#F6F6F6"],
    other_colors: [],
    num_of_colors: 7,
    topic: "environment",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Verdana, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Garamond, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": '"Segoe UI", sans-serif',
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#2E467F",
    context_color: "#AABEC4",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
  2444: {
    main_color: [
      "#CB4335",
      "#34608A",
      "#D6A12E",
      "#9E3A2F",
      "#E89A64",
      "#3A7D69",
      "#8B463E",
      "#AA7F2C",
      "#C4684A",
      "#5C5D6C",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#C3C3C3", "#536976", "#4D4D4D"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 5,
    topic: "economy, business and finance",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": "Georgia, serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Georgia, serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "bold",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
    },
    base_color: "#34608A",
    context_color: "#A09A9B",
    mapColorDefault: "#E5E0E2",
    mapColorLow: "#D9C8CC",
    mapColorHigh: "#A6858D",
  },
  1436: {
    main_color: [
      "#00C6AA",
      "#0071BA",
      "#009A98",
      "#D9BA00",
      "#C47F00",
      "#E2B96D",
      "#6C88A8",
      "#B1745C",
      "#8B5B9E",
      "#5A9B82",
    ],
    bcg: "#FCF7F7",
    context_colors: ["#CBCBCB", "#A1A1A1", "#516270"],
    similar_to_bcg: [],
    other_colors: [],
    num_of_colors: 6,
    topic: "lifestyle and leisure",
    text_color: "#333333",
    font: {
      title: {
        "font-size": "h1",
        "font-family": '"Trebuchet MS", sans-serif',
        "font-weight": "bold",
        "font-style": "normal",
      },
      description: {
        "font-size": "h2",
        "font-family": "Calibri, sans-serif",
        "font-weight": "normal",
        "font-style": "italic",
      },
      label: {
        "font-size": "h3",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      value: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
      },
      legend: {
        "font-size": "h4",
        "font-family": "Arial, sans-serif",
        "font-weight": "normal",
        "font-style": "italic",
      },
    },
    base_color: "#0071BA",
    context_color: "#94AFB9",
    mapColorDefault: "#D1E3E9",
    mapColorLow: "#B1D4E5",
    mapColorHigh: "#5A9BC6",
  },
};
